Update lint.yaml

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -16,21 +16,19 @@ jobs:
           node-version: '20'
 
   lint:
-      runs-on: ubuntu-latest
-      needs: setup
-      steps:
-        - uses: actions/checkout@v4
-        - name: Install modules
-          run: npm install
-        - name: Run ESLint
-          id: lint
-          run: npm run lint || echo "Linting failed"
-          continue-on-error: true
-  
-        - name: Attempt to fix lint errors
-          if: steps.lint.outcome == 'failure'
-          run: npm run lint-fix
-  
-        - name: Run ESLint again
-          if: steps.lint.outcome == 'failure'
-          run: npm run lint
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install modules
+        run: npm install
+      - name: Run ESLint
+        id: lint
+        run: npm run lint || echo "Linting failed"
+        continue-on-error: true
+      - name: Attempt to fix lint errors
+        if: steps.lint.outcome == 'failure'
+        run: npm run lint-fix  
+      - name: Run ESLint again
+        if: steps.lint.outcome == 'failure'
+        run: npm run lint
